export const ouGroupIndex=  {
  u52bDIwLiOG: 1,
  vTZ2yIeAi81: 2,
  QbaIyUsVHJ9: 3,
  qvN06qQw9Hr: 4,
  D5YO4NsZtSp: 5,
  qsRLv1WjuiM: 6,
  Y1P2f3awpzt: 7
}

export const fundsId = [
  "R0JHwxWssuD",
  "yzCH9OyAHf9",
  "ArM16lmaMz8;KJPVAwpIk0y",
  "CiLKJuIxMHh",
];
export const fundsIdYear = [
  "R0JHwxWssuD",
  "yzCH9OyAHf9",
  "ArM16lmaMz8;KJPVAwpIk0y",
];
export const scoresId = {
  "CHC / SDH": ["Pk9nPVbH9ux", "YaoJOjzhm97"],
  DH: ["Bf5FS8GIGsl", "sLV21OXx8Yr"],
  PHC: ["xGA2Lw12vQi", "TxBqFbp7YdF"],
  UPHC: ["xGA2Lw12vQi", "TxBqFbp7YdF"],
  INS: ["kxZYPry1cGD", "Cdn9FqbGXIx"],
  DHT: ["vEqxM04HXI6", "UtAsCh0j3tR"],
  SHT: ["cDGN8aQEIXp", "FpqYwDb1ZAm"],
};
export const IndicatorScoreId = {
  "CHC / SDH": [
    "wHeR9Hvw1Dj",
    "a5HC30I2dOD",
    "fohWNeyzgpi",
    "azCwG2yRAPe",
    "pAFhVVWWjwE",
    "hKjlqYAX0k3",
    "BhtXFAZakBM",
    "TfC4gb3yfF6",
    "zp4dtkWEp29",
    "CjovCpI9tCQ",
    "ahWO1BzOk0N",
    "LNuNHrvvzzY",
    "Ew3pCQkT0h6",
    "HLv8suT8gIj",
    "IBOzkgCd3Om",
    "OGW78PSv1zG",
    "dtHo9pu47Gb",
    "wfAFMsCDEg6",
    "jupf20PRBE3",
    "dqlTcJVFg6N",
  ],
  DH: [
    "zyeuAHHGHhk",
    "z5R5cT2FYpU",
    "pBKaPU3oX4q",
    "frzgARwUdnb",
    "CwdBDr1WqFh",
    "jWD0EdYyylY",
    "DFFZVXXlRr5",
    "Eb12q2g1ClU",
    "LrFYCQe6GYC",
    "aQT6upeOZRQ",
    "x93J1Ob9OtB",
    "KWBYEVjozvT",
    "BrYkWIAw28Z",
    "e02pSGJCmeD",
    "C9cHeXGpE0g",
    "znG5DXj4W1X",
    "m7HNXVzgYsm",
    "cx4MnP9DSUM",
    "jO7UBAEqZQV",
    "QaG3vi2esPV",
    "jwBkdvtsvpc",
    "j2K3OkE5jWX",
    "jt0Iu1MbUMC",
    "JOuucaWRGQ3",
  ],
  PHC: [
    "kYv6z40PUry",
    "ScbtoYqPXgC",
    "k6WL8QTahRx",
    "V75j3GmNl4F",
    "vE9FX7noI2B",
    "NbVCoMXdrNs",
    "i3IhffpHeVl",
    "MJJ3EUxjjKk",
    "UC2uPvPmH3B",
    "YZ8ju7yq2Rn",
    "zZa8EMGcYSA",
    "usaznFLM8LA",
    "roxV1Oz25wH",
    "D9QMcmWsDXD",
    "USrnj98vrY6",
    "Z7VNKSnj9bR",
    "t2MhPj0U4mQ",
    "MBXhuZ9OegK",
    "EMXIN8NrEP5",
  ],
  UPHC: [
    "kYv6z40PUry",
    "ScbtoYqPXgC",
    "k6WL8QTahRx",
    "V75j3GmNl4F",
    "vE9FX7noI2B",
    "NbVCoMXdrNs",
    "i3IhffpHeVl",
    "MJJ3EUxjjKk",
    "UC2uPvPmH3B",
    "YZ8ju7yq2Rn",
    "zZa8EMGcYSA",
    "usaznFLM8LA",
    "roxV1Oz25wH",
    "D9QMcmWsDXD",
    "USrnj98vrY6",
    "Z7VNKSnj9bR",
    "t2MhPj0U4mQ",
    "MBXhuZ9OegK",
    "EMXIN8NrEP5",
  ],
  INS: [
    "wlh7yTyHNYD",
    "EHOymTtAcPV",
    "AEIomIEhOsg",
    "TlJuoGUp1Xi",
    "gK6bljEJaNk",
    "ylEYRAam5nQ",
    "dJH1VH2O1lN",
    "pH76A1K26zP",
    "FETsjtz2kOw",
    "OjgZv1Y3r0K",
    "ozoDR9zjdKQ",
    "D4cocpkwCx9",
    "bx88kH1ekW8",
    "vZ9FIuSxhjc",
  ],
  DHT: [
    "KnLeylQaXFT",
    "coFSGq3mv0I",
    "Srq1cetNeHw",
    "Ew3SRGejnOX",
    "lEdconYLSaC",
    "LWKaITYzc9r",
    "Zps2HqHk1jb",
    "rOD9G31KkwG",
    "SwsOXNli8Y4",
    "D6kZSdtYXUj",
    "PlwhmZrWtvO",
  ],
  SHT: [
    "t74ltsSf68i",
    "Zqtv9m6tXIh",
    "NC2PIoZTM6z",
    "ociWIIMxm4Y",
    "frNOnokrMKo",
    "iLbWxAsF9XO",
    "oUSK4C7ysG0",
    "qeJzHGDSbPc",
    "fINfpV0hTRs",
    "kHerGhHlafN",
    "I5xIWOv1NVX",
    "EbWojBgvxOD",
    "wjBuomAHdr2",
    "qtEoIDQISfe",
    "e39Pp7oPc70",
    "rTkivTYNAMw",
  ],
};
